n1 = int(input("Enter Number 1 : "))
n2 = int(input("Enter Number 2 : "))
print("=== ARITHMETIC OPERATIONS ===")
print("Sum :",(n1+n2))
print("Difference :",(n1-n2))
print("Product :",(n1*n2))
print("Division :",(n1/n2))